global using Moq;
global using Xunit;
global using Ccalc.Core.Common;
global using Ccalc.Core.Parsing;
global using Ccalc.Core.Evaluation;
global using Ccalc.Core.Convertion;
global using Ccalc.Tests;
global using Ccalc.Tests.Unit.Core.Common;
global using Ccalc.Tests.Integration.Core.Common;